apiVersion: v1
kind: Secret
metadata:
  name: edge-signing-key
  namespace: arealis-zord
type: Opaque
stringData:
  ed25519_private.pem: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIJz8ZGsamdmojBOHIXTHD68xxjytpoBdUhzvCCKm9VeH
    -----END PRIVATE KEY-----
