apiVersion: v1
kind: Secret
metadata:
  name: edge-signing-key
  namespace: arealis-zord
type: Opaque
stringData:
  ed25519_private.pem: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_YOUR_ED25519_PRIVATE_KEY
    -----END PRIVATE KEY-----
