apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arealis-zord
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Arealis-network/Arealis-Zord.git
    targetRevision: prod
    path: k8s-file/kubernetes/argocd-full
  destination:
    server: https://kubernetes.default.svc
    namespace: arealis-zord
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

