apiVersion: apps/v1
kind: Deployment
metadata:
  name: zord-intent-engine
  namespace: arealis-zord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zord-intent-engine
  template:
    metadata:
      labels:
        app: zord-intent-engine
    spec:
      containers:
      - name: zord-intent-engine
        image: arealis/zord-intent-engine:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: INTENT_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: INTENT_DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: INTENT_DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zord-secrets
              key: INTENT_DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: INTENT_DB_NAME
        - name: DB_SSLMODE
          value: disable
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: KAFKA_BROKERS
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: KAFKA_TOPIC
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: INTENT_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: CANONICAL_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: zord-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: zord-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: ZORD_VAULT_KEY
          valueFrom:
            secretKeyRef:
              name: zord-secrets
              key: ZORD_VAULT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: zord-intent-engine
  namespace: arealis-zord
spec:
  selector:
    app: zord-intent-engine
  ports:
  - name: http
    port: 8083
    targetPort: 8083
