apiVersion: apps/v1
kind: Deployment
metadata:
  name: zord-token-enclave
  namespace: arealis-zord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zord-token-enclave
  template:
    metadata:
      labels:
        app: zord-token-enclave
    spec:
      containers:
      - name: zord-token-enclave
        image: arealis/zord-token-enclave:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8087
        env:
        - name: PORT
          value: "8087"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: TOKEN_DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: TOKEN_DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: TOKEN_DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zord-secrets
              key: TOKEN_DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: zord-config
              key: TOKEN_DB_NAME
        - name: DB_SSLMODE
          value: disable
        - name: MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: zord-secrets
              key: TOKEN_ENCLAVE_MASTER_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: zord-token-enclave
  namespace: arealis-zord
spec:
  selector:
    app: zord-token-enclave
  ports:
  - name: http
    port: 8087
    targetPort: 8087
