package persistence

import (
	"context"
	"database/sql"
	"errors"
	"time"

	"zord-intent-engine/internal/fetcher"
	"zord-intent-engine/internal/models"
)

type IngressEnvelopePostgresRepo struct {
	db *sql.DB
}

// Compile-time guarantee
var _ fetcher.RawEnvelopeRepository = (*IngressEnvelopePostgresRepo)(nil)

func NewIngressEnvelopeRepo(db *sql.DB) *IngressEnvelopePostgresRepo {
	return &IngressEnvelopePostgresRepo{db: db}
}

/*
Save persists a full ingress envelope.
Used when THIS service owns envelope creation.
*/
func (r *IngressEnvelopePostgresRepo) Save(
	ctx context.Context,
	env models.IngressEnvelope,
) (models.IngressEnvelope, error) {

	_, err := r.db.ExecContext(ctx, `
		INSERT INTO ingress_envelopes (
			envelope_id,
			tenant_id,
			source,
			idempotency_key,
			payload_hash,
			object_ref,
			parse_status,
			received_at
		) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
	`,
		env.EnvelopeID,
		env.TenantID,
		env.Source,
		env.IdempotencyKey,
		env.PayloadHash,
		env.ObjectRef,
		env.ParseStatus,
		env.ReceivedAt,
	)

	return env, err
}

/*
InsertDummy inserts a minimal ingress_envelopes row.

TEMPORARY:
Used while envelope_id is generated by upstream service.
This exists ONLY to satisfy FK constraints.
*/
func (r *IngressEnvelopePostgresRepo) InsertDummy(
	ctx context.Context,
	envelopeID string,
	tenantID string,
) error {

	_, err := r.db.ExecContext(ctx, `
		INSERT INTO ingress_envelopes (
			envelope_id,
			tenant_id,
			source,
			payload_hash,
			object_ref,
			parse_status,
			received_at
		) VALUES ($1,$2,'API','dummy','inline','PARSED',$3)
		ON CONFLICT (envelope_id) DO NOTHING
	`,
		envelopeID,
		tenantID,
		time.Now().UTC(),
	)

	return err
}

/*
FindByID fetches an ingress envelope by envelope_id.
*/
func (r *IngressEnvelopePostgresRepo) FindByID(
	ctx context.Context,
	envelopeID string,
) (models.IngressEnvelope, error) {

	var env models.IngressEnvelope

	err := r.db.QueryRowContext(ctx, `
		SELECT envelope_id, tenant_id, source, idempotency_key,
		       payload_hash, object_ref, parse_status, received_at
		FROM ingress_envelopes
		WHERE envelope_id = $1
	`, envelopeID).Scan(
		&env.EnvelopeID,
		&env.TenantID,
		&env.Source,
		&env.IdempotencyKey,
		&env.PayloadHash,
		&env.ObjectRef,
		&env.ParseStatus,
		&env.ReceivedAt,
	)

	if err == sql.ErrNoRows {
		return env, errors.New("envelope not found")
	}

	return env, err
}
