services:
  zord-prompt-layer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zord-prompt-layer
    ports:
      - "8086:8086"
    env_file:
      - .env
    
    networks:
      - zord-network
    restart: unless-stopped

networks:
  zord-network:
    external: true
    name: zord-shared-network
