import { NextRequest, NextResponse } from 'next/server'
import { SchemaEvolutionResponse } from '@/types/schema-evolution'

export const dynamic = 'force-dynamic'

export async function GET(request: NextRequest) {
  // Simulate API latency
  await new Promise(resolve => setTimeout(resolve, 100))

  const mockData: SchemaEvolutionResponse = {
    registry_health: {
      total_schemas: 15,
      active_schemas: 12,
      deprecated_schemas: 3,
      breaking_changes_30d: 1,
      schemas_with_failures: 2,
    },
    change_impact: {
      changes_30d: 4,
      breaking_changes_30d: 1,
      validations_30d: 8247,
      failures_30d: 19,
      failure_rate_change_percent: 47,
      top_failure_schema: 'payout.intent',
      top_failure_schema_count: 19,
    },
    schemas: [
      {
        schema_id: 'sch_payout_intent',
        schema_name: 'payout.intent',
        display_name: 'Payout Intent',
        status: 'ACTIVE',
        current_version: 'v1.3',
        total_versions: 3,
        breaking_changes_30d: 1,
        dlq_failures_30d: 19,
        affected_tenants_30d: ['acme_nbfc', 'foo_psp'],
        last_updated: '2026-01-13T12:00:00Z',
        owner_team: 'Engine',
        versions: [
          {
            version: 'v1.3',
            created_at: '2026-01-13T12:00:00Z',
            compatibility: 'BREAKING',
            backward_compatible: false,
            forward_compatible: false,
            deployed_to_prod: true,
            fields_added: [],
            fields_removed: [],
            fields_changed: ['beneficiary.ifsc: required→optional'],
            dlq_failures_24h: 19,
            affected_tenants: ['acme_nbfc', 'foo_psp'],
            created_by: 'ci-deploy@arealis.com',
          },
          {
            version: 'v1.2',
            created_at: '2026-01-10T09:30:00Z',
            compatibility: 'BACKWARD',
            backward_compatible: true,
            forward_compatible: false,
            deployed_to_prod: true,
            fields_added: ['metadata.priority'],
            fields_removed: [],
            fields_changed: [],
            dlq_failures_24h: 0,
            affected_tenants: [],
            created_by: 'ci-deploy@arealis.com',
          },
          {
            version: 'v1.1',
            created_at: '2026-01-07T14:15:00Z',
            compatibility: 'FULL',
            backward_compatible: true,
            forward_compatible: true,
            deployed_to_prod: true,
            fields_added: [],
            fields_removed: [],
            fields_changed: [],
            dlq_failures_24h: 0,
            affected_tenants: [],
            created_by: 'ci-deploy@arealis.com',
          },
        ],
      },
      {
        schema_id: 'sch_payment_confirm',
        schema_name: 'payment.confirmation',
        display_name: 'Payment Confirmation',
        status: 'ACTIVE',
        current_version: 'v2.1',
        total_versions: 5,
        breaking_changes_30d: 0,
        dlq_failures_30d: 0,
        affected_tenants_30d: [],
        last_updated: '2026-01-08T10:00:00Z',
        owner_team: 'Payments',
        versions: [
          {
            version: 'v2.1',
            created_at: '2026-01-08T10:00:00Z',
            compatibility: 'FULL',
            backward_compatible: true,
            forward_compatible: true,
            deployed_to_prod: true,
            fields_added: ['settlement_date'],
            fields_removed: [],
            fields_changed: [],
            dlq_failures_24h: 0,
            affected_tenants: [],
            created_by: 'ci-deploy@arealis.com',
          },
        ],
      },
      {
        schema_id: 'sch_webhook_event',
        schema_name: 'webhook.event',
        display_name: 'Webhook Event',
        status: 'ACTIVE',
        current_version: 'v1.4',
        total_versions: 4,
        breaking_changes_30d: 0,
        dlq_failures_30d: 0,
        affected_tenants_30d: [],
        last_updated: '2026-01-05T16:00:00Z',
        owner_team: 'Edge',
        versions: [
          {
            version: 'v1.4',
            created_at: '2026-01-05T16:00:00Z',
            compatibility: 'BACKWARD',
            backward_compatible: true,
            forward_compatible: false,
            deployed_to_prod: true,
            fields_added: ['retry_count'],
            fields_removed: [],
            fields_changed: [],
            dlq_failures_24h: 0,
            affected_tenants: [],
            created_by: 'ci-deploy@arealis.com',
          },
        ],
      },
      {
        schema_id: 'sch_batch_manifest',
        schema_name: 'batch.manifest',
        display_name: 'Batch Manifest',
        status: 'ACTIVE',
        current_version: 'v1.2',
        total_versions: 2,
        breaking_changes_30d: 0,
        dlq_failures_30d: 0,
        affected_tenants_30d: [],
        last_updated: '2026-01-02T08:00:00Z',
        owner_team: 'Batch',
        versions: [],
      },
      {
        schema_id: 'sch_audit_event',
        schema_name: 'audit.event',
        display_name: 'Audit Event',
        status: 'ACTIVE',
        current_version: 'v3.0',
        total_versions: 6,
        breaking_changes_30d: 0,
        dlq_failures_30d: 0,
        affected_tenants_30d: [],
        last_updated: '2025-12-28T11:00:00Z',
        owner_team: 'Compliance',
        versions: [],
      },
      {
        schema_id: 'sch_legacy_payment',
        schema_name: 'legacy.payment',
        display_name: 'Legacy Payment (Deprecated)',
        status: 'DEPRECATED',
        current_version: 'v0.9',
        total_versions: 3,
        breaking_changes_30d: 0,
        dlq_failures_30d: 0,
        affected_tenants_30d: [],
        last_updated: '2025-11-15T00:00:00Z',
        owner_team: 'Platform',
        versions: [],
      },
    ],
    recent_failures: [
      {
        failure_id: 'fail_001',
        timestamp: '2026-01-13T12:29:11Z',
        schema_name: 'payout.intent',
        schema_version: 'v1.3',
        reason_code: 'INVALID_FIELD',
        error_message: 'beneficiary.ifsc is required',
        tenant_id: '11111111-1111-1111-1111-111111111111',
        tenant_name: 'acme_nbfc',
        envelope_id: 'env_20260113T122911Z_twyh',
        dlq_id: 'dlq_20260113T123201Z_9A3F',
      },
      {
        failure_id: 'fail_002',
        timestamp: '2026-01-13T12:31:22Z',
        schema_name: 'payout.intent',
        schema_version: 'v1.3',
        reason_code: 'INVALID_SCHEMA',
        error_message: 'Schema version mismatch',
        tenant_id: '22222222-2222-2222-2222-222222222222',
        tenant_name: 'foo_psp',
        envelope_id: 'env_20260113T123122Z_xyz1',
        dlq_id: 'dlq_20260113T123201Z_8B2E',
      },
      {
        failure_id: 'fail_003',
        timestamp: '2026-01-13T12:33:45Z',
        schema_name: 'payout.intent',
        schema_version: 'v1.3',
        reason_code: 'FIELD_TYPE_MISMATCH',
        error_message: 'amount: expected number, got string',
        tenant_id: '11111111-1111-1111-1111-111111111111',
        tenant_name: 'acme_nbfc',
        envelope_id: 'env_20260113T123345Z_abc2',
        dlq_id: 'dlq_20260113T123345Z_7C1D',
      },
      {
        failure_id: 'fail_004',
        timestamp: '2026-01-13T12:35:00Z',
        schema_name: 'payout.intent',
        schema_version: 'v1.3',
        reason_code: 'INVALID_FIELD',
        error_message: 'beneficiary.ifsc is required',
        tenant_id: '11111111-1111-1111-1111-111111111111',
        tenant_name: 'acme_nbfc',
        envelope_id: 'env_20260113T123500Z_def3',
        dlq_id: 'dlq_20260113T123500Z_6D0E',
      },
      {
        failure_id: 'fail_005',
        timestamp: '2026-01-13T12:38:15Z',
        schema_name: 'payout.intent',
        schema_version: 'v1.3',
        reason_code: 'INVALID_FIELD',
        error_message: 'beneficiary.ifsc is required',
        tenant_id: '22222222-2222-2222-2222-222222222222',
        tenant_name: 'foo_psp',
        envelope_id: 'env_20260113T123815Z_ghi4',
        dlq_id: 'dlq_20260113T123815Z_5E9F',
      },
    ],
  }

  return NextResponse.json(mockData)
}
